### ISSUE TITLE
It looks like the city production panel is missing

### ISSUE THREAD

**Issue by MarkusKV** [Azurency/CQUI_Community-Edition#235] opened 2017-12-02 23:02 UTC
I did a pull to get the latest trunk, copied the files into right place, now I have no city production panel on the right.  I checked the local files using steam.  Maybe something got corrupted.  Nope.  Files are good.  Tried a few other things.  Maybe I've hidden the build panel by accident.  But, I can't find any way to show it.

Is this a bug?  Or, user error?

**Comment by thomco** [comment] 2017-12-02 23:13
I'm seeing the same as of today
Was this introduced by the latest checkin to the productionpanel lua? (commit 00c40b0)

**Comment by thomco** [comment] 2017-12-02 23:15
@MarkusKV are you playing as Persia?

**Comment by MarkusKV** [comment] 2017-12-02 23:22
No. Brazil. And as a test Kongo. 


Regards. Mark K Vallevand 


-------- Original message --------From: Thomas Coleman <notifications@github.com> Date: 12/2/17  5:15 PM  (GMT-06:00) To: Azurency/CQUI_Community-Edition <CQUI_Community-Edition@noreply.github.com> Cc: MarkusKV <mvallevand@q.com>, Mention <mention@noreply.github.com> Subject: Re: [Azurency/CQUI_Community-Edition] It looks like the city
  production panel is missing (#235) 
@MarkusKV are you playing as Persia?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azurency/CQUI_Community-Edition","title":"Azurency/CQUI_Community-Edition","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azurency/CQUI_Community-Edition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thomco in #235: @MarkusKV are you playing as Persia?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Azurency/CQUI_Community-Edition/issues/235#issuecomment-348727311"}}}

**Comment by thomco** [comment] 2017-12-02 23:23
Did you update from git today?
I backed out this morning's commit and it now works for me

**Comment by MarkusKV** [comment] 2017-12-02 23:45
Yes. Updated today.   I'll need to do the same and back out the changes.   Now where is my git cheat sheet? 


Regards. Mark K Vallevand 


-------- Original message --------From: Thomas Coleman <notifications@github.com> Date: 12/2/17  5:23 PM  (GMT-06:00) To: Azurency/CQUI_Community-Edition <CQUI_Community-Edition@noreply.github.com> Cc: MarkusKV <mvallevand@q.com>, Mention <mention@noreply.github.com> Subject: Re: [Azurency/CQUI_Community-Edition] It looks like the city
  production panel is missing (#235) 
Did you update from git today?

I backed out this morning's commit and it now works for me

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azurency/CQUI_Community-Edition","title":"Azurency/CQUI_Community-Edition","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azurency/CQUI_Community-Edition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@thomco in #235: Did you update from git today?\r\nI backed out this morning's commit and it now works for me   "}],"action":{"name":"View Issue","url":"https://github.com/Azurency/CQUI_Community-Edition/issues/235#issuecomment-348727734"}}}

**Comment by MarkusKV** [comment] 2017-12-03 00:11
Did the reset and I'm back on the air.

**Comment by stephentt-me** [comment] 2017-12-03 06:37
I can confirm this problem!
Screen shot:
![screen001](https://user-images.githubusercontent.com/25250133/33523038-085fa872-d82f-11e7-85c4-d94969bbd8a9.png)

**Comment by MarkusKV** [comment] 2017-12-03 13:04
No. You need to roll back your clone to the previous commit using git -reset. The master branch is still broken. 


Regards. Mark K Vallevand 


-------- Original message --------From: Stëphēn <notifications@github.com> Date: 12/3/17  12:39 AM  (GMT-06:00) To: Azurency/CQUI_Community-Edition <CQUI_Community-Edition@noreply.github.com> Cc: MarkusKV <mvallevand@q.com>, Mention <mention@noreply.github.com> Subject: Re: [Azurency/CQUI_Community-Edition] It looks like the city
  production panel is missing (#235) 
Hey, but this is the version I clone it (master) 30 minutes ago. I thought it's rolled back?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azurency/CQUI_Community-Edition","title":"Azurency/CQUI_Community-Edition","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azurency/CQUI_Community-Edition"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stephentt-me in #235: Hey, but this is the version I clone it (`master`) 30 minutes ago. I thought it's rolled back?"}],"action":{"name":"View Issue","url":"https://github.com/Azurency/CQUI_Community-Edition/issues/235#issuecomment-348744161"}}}

**Comment by Azurency** [comment] 2017-12-03 13:34
Ops, my mistake. Fixed now.

**Closed by Azurency** 2017-12-03 13:34 UTC

**Comment by MarkusKV** [comment] 2017-12-09 21:18
Did the reset and I'm back on the air.

**Comment by MarkusKV** [comment] 2017-12-09 21:19
Looks like its back.  If a city fails to complete a wonder, the production panel disappears.
